### ISSUE TITLE
Create Validator Not Working

### ISSUE THREAD

**Issue by joesixpack** [dfinance/testnet-bootstrap#7]
dnode version
v0.7.6
dncli version
v0.7.6

dncli tx staking create-validator \
  --amount=2500000000000000000000sxfi \
  --pubkey=walletvalconspub1zcjduepqsrwl56gqakt20d3jqxk7dpp8vcg53rq63jdrtr664cv0yzv488gqykr27f \
  --moniker=ou812 \
  --commission-rate="0.02" \
  --commission-max-rate="0.25" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="2500000000000000000000" \
  --from joesixpack

./dfinance-createvalidator.sh
Enter keyring passphrase:
ERROR: unknown address: account 06ED8B21E9F74E8C5AB862265B638E2B51EE90CF: not found

**Comment by borispovod** [comment]
@joesixpack your address is not existing, so not possible to create, you need to get some coins/tokens on it
closing for now, it's not bootstrap docker issue
